### ISSUE TITLE
Conference app [iOS & Android] and its theme

### ISSUE THREAD

**Issue by deekej** [devconfcz/devconfcz#5]
So, as we already discussed we need a new mobile application for the conference, which will have same united theme/look as the website itself, and will be easy to use and stable.

My suggestion is to use Conffa:
http://connfa.com/
https://opensource.com/life/16/2/connfa-open-source-conference-app

It's FOSS application. Basically we will need 2 major things:
- website design finished, so it can be reused in the application (this means logo, colors, design, etc.)
- someone who is capable in programming of mobile applications to modify the Conffa chasis to our design and our needs

This should really improve the UX of people visiting conference, and it can also work offline, so the WiFi shouldn't be an issue for this.

**Comment by garrett** [comment]
The site is currently down, but, thanks to the magic of Archive.org, I was able to look at it:
https://web.archive.org/web/20160624013230/http://connfa.com/
(and it looks great!)

The source is at:
- Android: https://github.com/lemberg/connfa-android
- iOS: https://github.com/lemberg/connfa-ios

I've pulled the source for each and it looks like the assets are in various PNG files, mainly for the icon, splash screen, and header — although icons within the app are also included as PNGs too (but those should remain looking like the platform, IMHO). 

There are some JPEGs included as well, but those are exclusively in the Android app, and should really be switched out for PNGs.

A good starting point is to look to see how other people have forked the repo and what changes they have made, and then do the same (but for DevConf). From a quick skim, it seems that it has been a mass rename (which probably went too far — as internal renames from drupalcon probably aren't really needed — only the external-facing changes should be really necessary) and a change of various graphics has been done: https://github.com/lemberg/connfa-android/compare/github-master...vladisac:github-master

**Comment by garrett** [comment]
I've included a spreadsheet with the image filenames of both projects, the width of the images, the height of the images, the aspect ratio, and a marker to indicate the first of a new aspect ratio (calculated)
[images-with-aspect.xlsx](https://github.com/kejbaly2/devconfcz/files/393484/images-with-aspect.xlsx)

Unfortunately, GitHub doesn't accept LibreOffice documents, so I had to export it to Excel... in the process, the conditional formatting to highlight Android vs. iOS was lost. :cry: On the plus side, this opens in LibreOffice again just fine otherwise. :wink:

I did sorting as follows:
- Aspect (desc)
- Width (desc)
- Filename (asc)

...with the idea that it would group similar images together (based on aspect ratio) even if they're sized differently or located in the two different projects. The width sorting was to make the larger original sizes bubble to the top. Filename sorting after that would try to keep similarly named files next to each other after that.

This is _all_ the images, so it's including platform icons and various image assets that really shouldn't be branded. I haven't filtered the list at all.

One big thing that sticks out is the huge JPEG (probably should be PNG, like the rest of the JPEGS) of the floorplan that is only found in the Android app — not in the iOS version.

**Comment by garrett** [comment]
Open source conference app alternatives I've found:

- Google's IO Schedule; Android Java; Apache license; seems to be Android-only: https://github.com/google/iosched
- FOSDEM; Android Java; Apache license; Android-only: https://github.com/cbeyls/fosdem-companion-android
- Xamarin Evolve; Xamarin C#; MIT license; Android, iOS, Windows 10 (phone, tablet, laptop): https://github.com/xamarinhq/app-evolve & https://blog.xamarin.com/download-the-xamarin-evolve-2016-conference-app/
- F8 Conference (Facebook); React Native; MIT license; Android, iOS; https://github.com/fbsamples/f8app/

The first two are Android only. The last two are cross-platform, but follow native guidelines (according to each). The advantage of the last two is that they're the same codebase and can output both iOS and Android apps, unlike Connfa, which is a separate codebase per platform (but still has iOS support in some form, unlike the first two options).

They're all open source and could all be customized for DevConf, naturally, and none of them are a bad choice (including Connfa).

It's probably best to support iOS also, if possible, so I guess that would limit the choices to Connfa, Evolve, or F8 derived apps.

The language might matter a bit — but probably wouldn't much really, as the idea is that we'd just swap out assets and names and recompile for the most part. Getting a build system to compile the apps might matter a bit, but they're all open source (these days at least), so it should all be fine.

It's probably most useful to install the various apps from the app stores to evaluate how well each one works and make a decision based on this experience.

**Comment by garrett** [comment]
I've now installed every one of the apps on my Android phone. They're all quite nice — and each has their pros and cons. The biggest issues with Evolve and F8 seem to be server components (although both appear to work offline too, once they have their data). As FOSDEM and IO are both Android-only, it looks like Connfa really is a great pick.

However, one issue with Connfa that the others don't seem to share: The mess of asset files, which I outlined above.

The way to move forward is to identify the different assets and make a build script for them so that the apps could share SVG sources which would only have to be changed in one place, and the script would output all of the files (and probably put the correct rendered assets in the right place).

**Comment by garrett** [comment]
Apparently, LibreOffice exports filters in Excel format, so here's an XLSX (sigh) with the list of probably-necessary-to-change graphics, sorted as above. It should be a good starting point to figure out which ones to recreate in SVG and what to output (PNGs as sizes and locations).
[images-with-aspect-filtered.xlsx](https://github.com/kejbaly2/devconfcz/files/393611/images-with-aspect-filtered.xlsx)

**Comment by kejbaly2** [comment]
wow, thanks much for the deep research. I'll take a look and comment soon

**Comment by deekej** [comment]
Man, that's some awesome work here! And I agree, there's a ****load of images there. Having an initial SVG to remove duplicates is a good idea, as well as the script to generate it properly.

Now it seems like a lot of work (and it is), but if we finish this, we will have one more less thing to worry about for the next year (and other DevConfs). I think it's worth the effort.

By the way, AFAIK, this year's summit had its own mobile app as well. I think we should ask the people behind what they used for it. :)

**Comment by garrett** [comment]
@deekej: Thanks! Good idea on asking the folks behind the Summit mobile app! Was there an iOS version as well as Android? Is it open sourced? (And if it isn't open source, then why not?)

It would also be nice to try to upstream any work we do into the Conffa itself, so everyone can benefit. (That is, if we go with Conffa.)

**Comment by garrett** [comment]
I've looked into it a bit and have some answers:

- Red Hat Summit Android app is at https://play.google.com/store/apps/details?id=com.spotme.redhatsummit14 — and the comments paint it as a really bad app.
- There's an iOS version @ https://itunes.apple.com/us/app/summit-and-devnation-2016/id833580435?mt=8
- There is a Windows phone version, oddly... https://www.microsoft.com/en-us/store/p/red-hat-summit/9nblggh0nbn8 (but this might be an old version?)
- It was made by [SpotMe.com](https://www.spotme.com/) and isn't open source (sigh).

That last point is the most important one, and I guess it means "this train terminates here". :sad:

Back to considering Connfa, I guess?

**Comment by garrett** [comment]
I took the data I made into a spreadsheet and then further transmogrified it into HTML and CSS to get a visual representation of the images:

https://people.redhat.com/glesage/project/devconf/conffa/conffa-images-with-aspect-filtered.html

(FWIW: ALL the images are in the file, but the non-relevant ones are filtered out in the CSS.)

**Comment by garrett** [comment]
The images are grouped by aspect ratio. You can see a few images will probably need to be slightly cropped. I'd suggest cropping so the top-left is always the top-left and the bottom would be lost, whenever the resize script is written.

**Comment by garrett** [comment]
I've updated it a bit. The big highlight is the literal highlight of Android (light green) and iOS (light blue). Just from the graphics, it seems that Android is the version with more features.

I've also bolded the platform (ios/android) and filename in the path+filename label.

**Comment by garrett** [comment]
The way this should work is: the first graphic in a group should be made as SVG. The rest of the similar ones in that group should be resized. If there's a similar one outside of the group, then that means it needs to be resized _and cropped_.

**Comment by deekej** [comment]
Sorry @garrett for the late reply, I was on a PTO last week. Anyway...

Having a proprietary mobile app on Summit is really pain in the ... *sigh* So I guess we should get back to Conffa, you already posted enough pros for it.

So I agree that we should upstream all the work we do here. This could also mean, that for next year's Summit we could have finally some FOSS app up and running. The DevConf would be a perfect testing ground for it. Seeing the ratings of current Summit app, we can't do much worse with Connfa.

And the lack of WindowsPhone support? Well, since Red Hat is partner with Microsoft now, maybe they could lend a hand afterwards, when the app is finished... :D *just a wish*

The cropping in the bottom right corner makes sense as well. We could prepare all the graphics in a way that all necessary stuff is in top left corner (close to the menu button in the app?) - those graphics illustrate it quite well.
